spring:
  cloud:
    stream:
      bindings:
        input:
          destination: input
        output:
          destination: output
        output-sink:
          destination: output
      default-binder: kafka
  kafka:
    client-id: square-finder
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

tpd:
  topic-name: advice-topic
  messages-per-request: 10

server:
  servlet:
    context-path: /wave

kafka:
  topic:
    input: input
    output: outputStream
