spring:
  application:
    name: kafka
  cloud:
    stream:
      bindings:
        #startOffset: latest
        INPUTUSERSTREAMSTRINGBUILDER:
          destination: INPUTUSERSTREAMSTRINGBUILDER
        output:
          destination: bar

server:
  servlet:
    context-path: /wave
